version: '3.11'

services:
  db_container:
    image: postgres:14.3-alpine3.15
    ports:
          - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}



  server:
    depends_on:
      - db_container
    build: .
    env_file: .env
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: always